export interface TermDefinition {
  term: string;
  fullName: string;
  brief: string;
  explanation?: string;
  learnMore?: string;
  canonicalSpec?: string;
  educationalNote?: string;
}

export const terms: Record<string, TermDefinition> = {
  'C(rho)': {
    term: 'C(\u03C1)',
    fullName: 'Coherence Function',
    brief: 'Maps presence to coherence: C(\u03C1) = tanh(\u03B3 ln(\u03C1/\u03C1_crit + 1)). A sigmoid/compander function, not an order parameter.',
    explanation: 'The central equation of Synchronism. Takes presence (\u03C1) \u2014 the density of compatible structural elements within a Markov Relevancy Horizon \u2014 and returns a coherence value between 0 and 1. Physical density (g/cm\u00B3) is one form of presence, but presence also encompasses temperature, energy levels, catalytic surfaces, and other factors that support emergence.',
    educationalNote: '\u26A0 Physicist note: C is NOT quantum phase coherence. Quantum-coherent systems (BEC, BCS, superconductors) sit at LOW C because they have large N_corr \u2192 small \u03B3. C measures density-driven collective ordering, the opposite of the standard CM usage.',
    learnMore: '/coherence-function',
  },
  '\u03B3': {
    term: '\u03B3',
    fullName: 'Gamma Parameter',
    brief: 'Transition-sharpness exponent: \u03B3 = 2/\u221AN_corr. A motivated ansatz, not a derivation.',
    explanation: 'Large \u03B3 (few correlated units \u2014 a single electron: N_corr = 1, \u03B3 = 2) gives a sharp C(\u03C1) transition; small \u03B3 (many correlated units \u2014 a crystal: \u03B3 \u2248 10\u207B\u00B9\u00B2) gives a flat one. \u03B3 \u2248 1 marks the sparse/collective boundary where chemistry clusters. Note the inversion: the most collective systems get the FLATTEST curves \u2014 BCS superconductors land at C \u2248 0. (This entry previously stated the regimes backwards \u2014 "\u03B3 << 1 quantum, \u03B3 >> 1 classical" \u2014 corrected 2026-06-12.) Structurally, \u03B3 is claimed to encode MRH coupling density (\u03B3 \u221D \u03BB\u00B7K/D, where \u03BB = interaction strength, K = connectivity, D = dimensionality), but no protocol independently measures N_corr in any system.',
    learnMore: '/gamma-parameter',
  },
  'N_corr': {
    term: 'N_corr',
    fullName: 'Correlation Number',
    brief: 'Number of particles moving as a correlated unit.',
    explanation: 'The fundamental input to \u03B3 = 2/\u221AN_corr. A single electron has N_corr = 1 (\u03B3 = 2, quantum). A crystal lattice might have N_corr = 10\u00B2\u2074 (\u03B3 \u2248 10\u207B\u00B9\u00B2, classical).',
    learnMore: '/gamma-parameter',
  },
  '\u03C1_crit': {
    term: '\u03C1_crit',
    fullName: 'Reference Density (Saturation Knee)',
    brief: 'Reference density \u2014 a saturation knee, not a critical point. C(\u03C1_crit, \u03B3=2) = 0.88; the midpoint C=0.5 sits at \u03C1 \u2248 0.32\u00D7\u03C1_crit. \u03C1_crit = A \u00D7 V_flat\u00B2 (astrophysical case).',
    explanation: '\u03C1_crit sets the scale at which the coherence function enters saturation \u2014 NOT a phase-transition critical density. At \u03B3=2, C(\u03C1_crit) = tanh(2\u00B7ln 2) = 0.88; the actual C=0.5 midpoint is at \u03C1 \u2248 0.32\u00D7\u03C1_crit. The "+1" regulator in ln(\u03C1/\u03C1_crit + 1) makes the function asymmetric. "Critical density" or "transition density" are misleading terms for this parameter \u2014 the correct description is saturation knee or reference density.',
    learnMore: '/critical-density',
  },
  'MRH': {
    term: 'MRH',
    fullName: 'Markov Relevancy Horizon',
    brief: 'An "event horizon for influence" \u2014 the bubble of nearest neighbors that matter. Everything outside it can be ignored without losing predictive accuracy.',
    explanation: 'Think of an atom: Andromeda exists, but its gravitational and electromagnetic influence on a single atom is below the noise floor. The MRH is the minimal neighborhood such that removing anything inside degrades prediction, and adding anything outside does not improve it. Formally: the minimal set of interacting degrees of freedom whose state transitions materially influence coherence evolution. In quantum mechanics, crossing the MRH IS measurement/decoherence. Presence (\u03C1) is defined relative to an MRH: change the MRH, presence changes.',
    learnMore: '/mrh',
  },
  'presence': {
    term: 'Presence (\u03C1)',
    fullName: 'Compatible Structural Elements within MRH',
    brief: 'How much compatible stuff is nearby \u2014 "density" but generalized. A single word for "the right kind of neighbors within your MRH."',
    explanation: 'Why not just call it density? Physical density (g/cm\u00B3) is one form of presence, but the framework applies the same equation to chemistry (presence = compatible molecular configurations), neural tissue (presence = coupled neurons), and galaxies (presence = baryonic density). A single word covers all these cases. Presence is not merely quantity \u2014 it encodes compatibility, configuration, and environmental suitability: \u03C1 = f(compatibility vector), the scalar projection of a multidimensional compatibility space onto a single number. Must be quantifiable, domain-transparent, MRH-dependent, and falsifiable.',
    learnMore: '/coherence-function',
  },
  'a\u2080': {
    term: 'a\u2080',
    fullName: 'MOND Acceleration Scale',
    brief: 'Milgrom\'s acceleration constant: a\u2080 = cH\u2080/(2\u03C0) \u2248 1.08\u00D710\u207B\u00B9\u2070 m/s\u00B2.',
    explanation: 'In MOND, this is a fundamental constant. In Synchronism, it EMERGES from cosmology \u2014 it\'s the Hubble acceleration divided by 2\u03C0. This is one of Synchronism\'s strongest results.',
    learnMore: '/mond-unification',
  },
  'RAR': {
    term: 'RAR',
    fullName: 'Radial Acceleration Relation',
    brief: 'Tight correlation between observed and baryonic acceleration in galaxies.',
    explanation: 'Discovered in SPARC data: what you see (baryonic matter) predicts what you get (total gravitational acceleration) with very small scatter. Synchronism predicts the scatter should be environment-dependent.',
    learnMore: '/galaxy-rotation',
  },
  'BTFR': {
    term: 'BTFR',
    fullName: 'Baryonic Tully-Fisher Relation',
    brief: 'Empirical power-law between a galaxy\'s total baryonic mass and its flat rotation velocity: M_bar ∝ V_flat^n.',
    explanation: 'The BTFR is one of the tightest empirical relations in galaxy dynamics: baryonic mass (stars + gas) scales as a power law of the asymptotic flat rotation velocity. The slope n depends on the sample regime: n → 4 in deep-MOND galaxies (SPARC-dominated), n ≈ 2.75 for transition-regime full samples (Synchronism Session 193), n → 2 near-Newtonian. Lelli et al. 2019 found n = 3.85 ± 0.09 for the SPARC deep-MOND-dominated sample — consistent with the regime-dependent prediction. The BTFR is a textbook MOND signature; a positive result would be consistent with both MOND and Synchronism.',
    learnMore: '/tier-1-existing',
  },
  'A2ACW': {
    term: 'A2ACW',
    fullName: 'AI-to-AI Adversarial Collaboration Workshop',
    brief: 'Protocol where AI agents stress-test each other\'s claims.',
    explanation: 'One agent defends a claim, another demands operational definitions and falsification criteria. Produces falsifiable test cards and forces precision.',
    learnMore: '/a2acw',
  },
  '\u03BE': {
    term: '\u03BE',
    fullName: 'Compression Action',
    brief: 'Alternative formulation: \u03BE = topology + geometry + dynamics.',
    explanation: 'The compression action variable unifies matter (topology), gravity (geometry), and quantum mechanics (dynamics) into a single parameter that feeds into the coherence function.',
    learnMore: '/compression-action',
  },
  'SPARC': {
    term: 'SPARC',
    fullName: 'Spitzer Photometry & Accurate Rotation Curves',
    brief: 'Database of 175 galaxies with precise rotation curves and mass models.',
    explanation: 'The gold-standard dataset for testing galaxy rotation theories. Synchronism was tested against all 175 galaxies.',
    learnMore: '/galaxy-rotation',
  },
  'ALFALFA-SDSS': {
    term: 'ALFALFA-SDSS',
    fullName: 'Arecibo Legacy Fast ALFA × Sloan Digital Sky Survey',
    brief: 'A cross-matched catalog of ~15,000 galaxies combining 21-cm HI gas masses (ALFALFA) with optical properties and environment metrics (SDSS).',
    explanation: 'ALFALFA (Arecibo Legacy Fast ALFA) mapped HI 21-cm radio emission from nearby galaxies, providing gas masses and rotation widths. Cross-matching with SDSS gives stellar masses, star formation rates, and large-scale environment metrics. The combined ALFALFA-SDSS catalog was used to test Synchronism\'s environment-dependent RAR scatter prediction (TEST-03). Result: R² = 0.14, below the pre-registered kill criterion of R² > 0.20 — the test failed.',
    learnMore: '/galaxy-rotation',
  },
  'NP2': {
    term: 'NP2',
    fullName: 'New Prediction #2',
    brief: 'Synchronism\'s prediction that RAR scatter depends on environment.',
    explanation: 'Standard models predict RAR scatter is constant. Synchronism predicts it varies with local density. Statistical test: p = 5\u00D710\u207B\u2076, strongly supported.',
    learnMore: '/rar-scatter',
  },
  '\u03B7': {
    term: '\u03B7',
    fullName: 'Reachability Factor',
    brief: 'Superconductivity parameter equivalent to Abrikosov-Gor\'kov pair-breaking efficiency.',
    explanation: 'Synchronism independently derived this factor, which turned out to match a known 1960 result. An honest reparametrization, not a new discovery.',
    learnMore: '/superconductivity',
    educationalNote: 'Marked as reparametrization \u2014 this is known physics in new notation.',
  },
  'coherence': {
    term: 'Coherence',
    fullName: 'Collective Behavior Measure',
    brief: 'How collectively a group of elements behaves, from sparse/independent (0) to dense/collective (1).',
    explanation: 'Low coherence (C\u21920): elements act independently \u2014 sparse matter, individual particles. High coherence (C\u21921): extremely dense, tightly packed systems \u2014 neutron stars, not superconductors. \u26A0 Terminology note for physicists: Synchronism uses "coherence" to mean density-driven classical ordering, NOT quantum phase coherence. Quantum-coherent systems (BEC, BCS superconductors) have large N_corr \u2192 small \u03B3 \u2192 LOW C in this framework. C=0 does not mean "incoherent" in the quantum sense; it means sparsely interacting. The key physics is density and collective behavior, not quantum-vs-classical character.',
    educationalNote: '\u26A0 Physicist terminology note: Synchronism "coherence" is NOT quantum phase coherence. In condensed matter, quantum-coherent systems (BEC, BCS superconductors) are maximally quantum-coherent \u2014 but they have large N_corr \u2192 small \u03B3 \u2192 LOW C in this framework. C=0 does not mean "incoherent" in the CM sense; it means sparsely interacting. C measures density-driven collective behavior, the opposite of the standard quantum-coherence usage. See also: C(\u03C1) entry, Mean-Field Theory entry.',
    learnMore: '/coherence-function',
  },
  'phase transition': {
    term: 'Phase Transition',
    fullName: 'Abrupt Change in System Behavior',
    brief: 'A sudden shift in how a system behaves, like water freezing or a magnet losing its magnetism.',
    explanation: 'In Synchronism, the quantum-to-classical transition is modeled as a phase transition controlled by \u03B3. At \u03B3 \u2248 1, systems sit right at the boundary \u2014 where chemistry, biology, and the most interesting physics occur.',
    learnMore: '/phase-transitions',
  },
  'reparametrization': {
    term: 'Reparametrization',
    fullName: 'Known Physics in New Notation',
    brief: 'When a result turns out to be equivalent to existing physics expressed in different variables.',
    explanation: 'Several Synchronism results (e.g., the \u03B7 reachability factor = Abrikosov-Gor\u2019kov pair-breaking) are reparametrizations. The site marks these honestly with orange badges. The novelty is in unification, not in each individual result.',
    learnMore: '/honest-assessment',
    educationalNote: 'Not a failure \u2014 reparametrizations confirm the framework is consistent with known physics, but they don\u2019t count as new predictions.',
  },
  'tanh': {
    term: 'tanh',
    fullName: 'Hyperbolic Tangent',
    brief: 'A mathematical function that smoothly maps any input to a value between \u22121 and +1 (or 0 and 1 when shifted).',
    explanation: 'In Ising mean-field theory, tanh arises naturally from the self-consistency loop m = tanh(\u03b2Jz\u00b7m). In Synchronism, there is no such self-consistency \u2014 the tanh shape is a phenomenological choice motivated by Landau-universality. Any sigmoid (logistic, erf, arctan, Hill) satisfying the same boundary conditions would be an equally valid choice. See /parameter-derivations for the explicit disclaimer.',
    learnMore: '/coherence-function',
  },
  'kill criterion': {
    term: 'Kill criterion',
    fullName: 'Falsification Threshold',
    brief: 'A specific, pre-registered outcome that would falsify a prediction if observed.',
    explanation: 'Each Tier-1 test has a kill criterion: a numerical threshold that, if crossed, means the framework\'s prediction is wrong. Example: TEST-02 kill is "wide-binary anomaly is independent of local stellar density." Kill criteria are stated before the data is analyzed, not after \u2014 this is what makes them falsifying rather than rationalizing. The set of kill criteria is the framework\'s most important methodological contribution.',
    learnMore: '/test-catalog',
  },
  'mean-field theory': {
    term: 'Mean-Field Theory',
    fullName: 'Average-Interaction Approximation',
    brief: 'A physics approach where each particle feels the average effect of all others, not individual interactions.',
    explanation: 'Simplifies many-body problems by replacing complex particle-by-particle interactions with a single "mean field." In the Ising model, the self-consistency condition m = tanh(βJz·m) is a fixed-point equation — m appears on both sides, tanh is the self-consistent solution, and the result is genuine spontaneous symmetry breaking with critical exponents. C(ρ) borrows the tanh *form* but is not derived this way: its argument is ρ (external density), not the order parameter itself. There is no fixed-point equation, no free energy minimized, no SSB, and no critical exponents — the Honest Assessment labels this a "Category Error." C(ρ) belongs to the compander family (μ-law/Hill/Naka–Rushton), not the mean-field class.',
    learnMore: '/parameter-derivations',
  },
  '\u039BCDM': {
    term: '\u039BCDM',
    fullName: 'Lambda Cold Dark Matter',
    brief: 'The standard model of cosmology: the universe is ~68% dark energy (\u039B), ~27% cold dark matter, ~5% ordinary matter.',
    explanation: 'The mainstream cosmological framework that explains the universe\'s expansion, galaxy formation, and cosmic microwave background. Synchronism doesn\'t replace \u039BCDM \u2014 it proposes an alternative interpretation of what "dark matter" represents (coherence effects rather than invisible particles).',
    learnMore: '/dark-matter-reframed',
  },
  'MOND': {
    term: 'MOND',
    fullName: 'Modified Newtonian Dynamics',
    brief: 'An alternative to dark matter: gravity behaves differently at very low accelerations (below a\u2080 \u2248 1.2\u00D710\u207B\u00B9\u2070 m/s\u00B2).',
    explanation: 'Proposed by Milgrom in 1983. Successfully predicts galaxy rotation curves without dark matter. Synchronism claims to derive MOND\'s acceleration constant a\u2080 from cosmological parameters, making it emergent rather than fundamental.',
    learnMore: '/mond-unification',
  },
  'V_flat': {
    term: 'V_flat',
    fullName: 'Flat Rotation Velocity',
    brief: 'The constant speed at which stars orbit in the outer parts of a galaxy.',
    explanation: 'Galaxy rotation curves show that stars far from the center orbit at roughly constant speed instead of slowing down (as Newton predicts). This "flat" velocity is the key observable that reveals the dark matter problem.',
    learnMore: '/galaxy-rotation',
  },
  'qualia': {
    term: 'Qualia',
    fullName: 'Subjective Experience',
    brief: 'The "what it\'s like" of conscious experience \u2014 the redness of red, the pain of pain.',
    explanation: 'In Synchronism, qualia are modeled as coherence resonance patterns that emerge when C crosses \u2248 0.50. This is speculative and untested. The site marks all consciousness claims with appropriate caveats.',
    learnMore: '/qualia-as-coherence',
    educationalNote: 'All consciousness predictions are untested. This is the most speculative part of the framework.',
  },
  'falsifiability': {
    term: 'Falsifiability',
    fullName: 'Can Be Proven Wrong',
    brief: 'A prediction is falsifiable if there exists an observation that would disprove it.',
    explanation: 'Every Synchronism prediction has a defined "kill criterion" \u2014 a specific outcome that would falsify it. This is what separates testable science from unfalsifiable speculation. The site documents both successful and failed predictions.',
    learnMore: '/falsifiability',
  },
  'badge-postdiction': {
    term: 'Post-diction',
    fullName: 'Validation Label: Post-diction',
    brief: 'Formula or derivation produced after the confirming experiment was already published.',
    explanation: 'A post-diction matches known data but was not a forward prediction — the experiment\'s result was already in the literature when the formula was derived. Epistemically weaker than "Validated" (genuine pre-registered prediction confirmed) but distinct from "Reparametrization" (notation change). Post-dictions can be valuable as consistency checks and can motivate forward predictions, but they do not independently confirm a framework.',
    learnMore: '/research-philosophy',
  },
  'badge-active-mrh': {
    term: 'Active-MRH (badge)',
    fullName: 'MRH-Relationship Badge: Active-MRH',
    brief: 'Currently in active research focus; being extended or revised.',
    explanation: 'MRH-relationship badges describe how a claim sits in the current research inventory, preferred for in-flight work. Active-MRH means the claim is under live investigation. At the current stewardship stage nothing is honestly characterizable as "established," so verdict-shaped tags like Validated are avoided.',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'badge-parallel-paths': {
    term: 'Parallel-Paths (badge)',
    fullName: 'MRH-Relationship Badge: Parallel-Paths',
    brief: 'In the framework\'s parallel hypothesis space; not currently in active focus but not abandoned.',
    explanation: 'Parallel-Paths means the claim is on the shelf — not being actively investigated but not disowned. The framework maintains multiple parallel research tracks simultaneously; Parallel-Paths marks a track that is not the current priority.',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'badge-sidelined': {
    term: 'Sidelined (badge)',
    fullName: 'MRH-Relationship Badge: Sidelined',
    brief: 'Was in active focus; currently not pursued; reasons documented; reactivation condition specified.',
    explanation: 'Sidelined differs from Parallel-Paths: the claim was actively worked and then explicitly deprioritized for documented reasons. To reactivate a Sidelined claim, the specified condition must be met (e.g., new data, resolution of a prior contradiction).',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'badge-superseded': {
    term: 'Superseded (badge)',
    fullName: 'MRH-Relationship Badge: Superseded',
    brief: 'Replaced by a later formulation; pointer to successor.',
    explanation: 'A Superseded claim was not wrong per se — it was absorbed into a more general or more precise successor. The pointer to the successor is part of the badge.',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'badge-audited-negative': {
    term: 'Audited-Negative (badge)',
    fullName: 'MRH-Relationship Badge: Audited-Negative',
    brief: 'Closed audit finding on a historical track; durable negative result; does not move.',
    explanation: 'Audited-Negative is the strongest closure badge. It means an explicit audit found the claim false, contradicted by data, or internally inconsistent — and this finding is a permanent part of the record. Examples: A-from-Jeans (closed 2026-06-07: Session 66 script gives A≈4.6×10⁻⁵, 600× off under the framework\'s own scaling); RAR γ=2 (ΔBIC=+184, rejected).',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'badge-validated': {
    term: 'Validated',
    fullName: 'Validation Badge: Validated (Deprecated)',
    brief: '\u26a0 Deprecated \u2014 no claim currently holds this badge. See Honest Assessment for the current badge system (Reparametrization, Failed, Untested, Speculative).',
    explanation: '\u26a0 This badge is deprecated. The 0 of 6 "Validated" claims that survived expert audit were all demoted to Reparametrization or Failed. "Validated" conflicts with the current stewardship discipline (nothing is honestly characterizable as established at this stage). In new content, use Active-MRH, Reparametrization, or the appropriate descriptive tag instead. Historical note: "Validated" meant the numbers agreed quantitatively with data \u2014 but agreement alone does not establish novelty; reparametrizations of known physics can "validate" without adding new physics.',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'badge-untested': {
    term: 'Untested',
    fullName: 'Validation Badge: Untested',
    brief: 'A specific prediction exists, but the relevant data or experiment has not been run.',
    explanation: '"Untested" is not a failure \u2014 it means nobody has looked yet. Many Synchronism predictions in astrophysics and quantum measurement are Untested because this lab cannot run experiments and the specific test has not been done by others.',
    learnMore: '/honest-assessment',
  },
  'badge-failed': {
    term: 'Failed',
    fullName: 'Validation Badge: Failed',
    brief: 'Prediction was tested and contradicted by data, with a specific error documented.',
    explanation: 'Failed predictions are not removed \u2014 they are documented with the exact error. Examples: YBCO T_c predicted 607K (observed 93K, 6.5\u00d7 error); Bullet Cluster dark matter viscosity sign wrong. Failures stay visible.',
    learnMore: '/honest-assessment',
  },
  'badge-speculative': {
    term: 'Speculative',
    fullName: 'Validation Badge: Speculative',
    brief: 'A conceptual proposal without a specific quantitative test defined.',
    explanation: 'Speculative claims are ideas the framework motivates but has not turned into falsifiable predictions. They may become testable with more development. Higher epistemic risk than Untested, which has a defined test.',
    learnMore: '/honest-assessment',
  },
  'badge-reparametrization': {
    term: 'Reparametrization (badge)',
    fullName: 'Validation Badge: Reparametrization',
    brief: 'The result is mathematically equivalent to existing physics expressed in different variables.',
    explanation: 'A reparametrization is not a failure \u2014 it shows the framework is consistent with known physics. But it is not a new prediction. Example: the \u03b7 reachability factor = Abrikosov-Gor\u2019kov pair-breaking (1960). The honest assessment tracks reparametrizations separately from genuinely novel predictions.',
    learnMore: '/honest-assessment',
  },
  'badge-strongly-supported': {
    term: 'Strongly Supported',
    fullName: 'Validation Badge: Strongly Supported (Deprecated)',
    brief: '\u26a0 Deprecated \u2014 conflicts with current stewardship discipline. Use Reparametrization, Untested, or Active-MRH instead.',
    explanation: '\u26a0 This badge is deprecated. It conflicts with the stewardship principle that nothing is honestly characterizable as "established" at the current stage. Historical meaning: the data supported the claim with high significance but with caveats (prior art, limited R\u00b2, non-independent explanation). Existing usages are being migrated to the current badge system (Reparametrization, Failed, Untested, Speculative, Active-MRH). See Honest Assessment for the canonical badge definitions.',
    learnMore: '/honest-assessment#validation-badge-definitions',
  },
  'CRT analogy': {
    term: 'CRT Analogy',
    fullName: 'Superposition as Temporal Scanning',
    brief: 'An electron beam scans so fast it appears everywhere at once. Measurement = sampling at different sync rates.',
    explanation: 'A CRT display\u2019s electron beam creates different perceptions depending on sampling rate: a stable image (slow), flickering bands (medium), or a single dot (fast). Nothing about the screen changes \u2014 only synchronization timing. Synchronism claims quantum phenomena work the same way: superposition is temporal scanning, collapse is catching the dot, and entanglement is two synchronized screens.',
    learnMore: '/two-reframes',
  },
  'raster entanglement': {
    term: 'Raster Entanglement',
    fullName: 'Entanglement as Synchronized Scanning',
    brief: 'Two patterns cycling in perfect sync show identical behavior regardless of distance. No information travels between them.',
    explanation: 'Like two CRT screens displaying identical pictures from synchronized electron beams: sample either screen at any rate, and both show the same thing simultaneously. Not because information traveled, but because their cycles were correlated from the start. Synchronism\u2019s explanation for quantum entanglement.',
    learnMore: '/two-reframes',
  },
  'decoherence': {
    term: 'Decoherence',
    fullName: 'Loss of Quantum Behavior',
    brief: 'The process by which quantum superpositions break down and systems start behaving classically.',
    explanation: 'In standard physics, decoherence occurs through interaction with the environment. In Synchronism, decoherence IS the MRH crossing \u2014 when correlations extend beyond the Markov Relevancy Horizon, quantum behavior transitions to classical.',
    learnMore: '/decoherence-mrh',
  },
  'ln': {
    term: 'ln',
    fullName: 'Natural Logarithm',
    brief: 'The logarithm base e (\u2248 2.718). Compresses very large ranges into manageable numbers.',
    explanation: 'ln(x) answers: "what power must I raise e to, to get x?" For example, ln(1) = 0, ln(e) = 1, ln(100) \u2248 4.6. In the coherence function C(\u03c1) = tanh(\u03b3 \u00b7 ln(\u03c1/\u03c1_crit + 1)), the natural log compresses the enormous density range of physical systems (interstellar gas to neutron stars spans 80+ orders of magnitude) into a range that tanh can differentiate. The "+1" inside the log ensures the argument is always \u2265 1, so ln \u2265 0 and C \u2265 0.',
    learnMore: '/coherence-function',
  },
  'baryon': {
    term: 'Baryon',
    fullName: 'Ordinary Matter Particle',
    brief: 'Protons, neutrons, and everything made of them \u2014 the ordinary matter you can touch.',
    explanation: '"Baryonic matter" means ordinary matter (atoms, stars, gas, dust) as opposed to dark matter or dark energy. About 5% of the universe\'s total energy content is baryonic. When galaxy rotation pages mention "baryonic mass" or "baryon density," they mean the mass of ordinary visible matter \u2014 the stars, gas, and dust you can actually observe.',
    learnMore: '/galaxy-rotation',
  },
  'BAO': {
    term: 'BAO',
    fullName: 'Baryon Acoustic Oscillations',
    brief: 'A characteristic spacing (~150 Mpc) imprinted in galaxy distributions by sound waves in the early universe.',
    explanation: 'Before the universe cooled enough for atoms to form, matter and light were coupled in a hot plasma. Sound waves propagated through this plasma, and when atoms formed (at "recombination"), these waves froze in place. Today, galaxies are preferentially spaced ~150 Mpc apart \u2014 a "standard ruler" used to measure the universe\'s expansion history. Synchronism\'s TEST-04 predicts a ~10\u207b\u2074 shift in this spacing between high- and low-density environments.',
    learnMore: '/bao-coherence-modulation',
  },
  'DESI': {
    term: 'DESI',
    fullName: 'Dark Energy Spectroscopic Instrument',
    brief: 'A large-scale sky survey at Kitt Peak Observatory measuring galaxy spectra to map cosmic expansion.',
    explanation: 'DESI (Dark Energy Spectroscopic Instrument) is a spectroscopic survey that measures the redshifts of ~40 million galaxies and quasars to map the universe\'s large-scale structure. DESI Data Release 1 (DR1, 2024) provided the most precise measurements to date of f\u03c3\u2088 (the combined growth-rate parameter) across multiple redshift bins. Synchronism\'s TEST-04a predicted f\u03c3\u2088(z=0.51) \u2248 0.418, below \u039bCDM; DESI DR1 observed \u2248 0.55 \u00b1 0.06, above \u039bCDM. This 2.4\u03c3 disagreement is the framework\'s first adjudication by external data.',
    learnMore: '/honest-assessment',
  },
  'sigma8': {
    term: '\u03c3\u2088',
    fullName: 'Matter Fluctuation Amplitude',
    brief: 'Measures how "lumpy" the universe is on 8 Mpc/h scales. A key cosmological parameter.',
    explanation: '\u03c3\u2088 (sigma-8) quantifies the amplitude of matter density fluctuations on scales of 8 Megaparsecs per h (where h is the dimensionless Hubble constant). A higher \u03c3\u2088 means galaxies clump more strongly; a lower \u03c3\u2088 means smoother distribution. Planck CMB data gives \u03c3\u2088 \u2248 0.83; weak-lensing surveys (KiDS, DES) give \u03c3\u2088 \u2248 0.77\u20130.80. This "S\u2088 tension" is an active area of cosmology. Synchronism Session 107 predicted \u03c3\u2088 \u2248 0.76; DESI DR1 measures \u03c3\u2088 = 0.841 \u00b1 0.034, disfavoring the prediction at 2.4\u03c3.',
    learnMore: '/honest-assessment',
  },
  'fsigma8': {
    term: 'f\u03c3\u2088',
    fullName: 'Growth-Rate \u00d7 Amplitude Parameter',
    brief: 'The product of the growth rate f(z) and the matter fluctuation amplitude \u03c3\u2088 \u2014 a key observable for structure growth.',
    explanation: 'f\u03c3\u2088(z) combines two cosmological measurements: f(z) = d(ln D)/d(ln a), the logarithmic growth rate of structure (how fast overdensities grow), and \u03c3\u2088(z), the amplitude of matter fluctuations at redshift z. Together they quantify how rapidly large-scale structure is building up. Higher f\u03c3\u2088 = faster growth = more clustering. Synchronism Session 107 predicted f\u03c3\u2088(z=0.51) \u2248 0.418, below \u039bCDM (\u22480.474). DESI DR1 measured \u22480.55 \u00b1 0.06, above \u039bCDM \u2014 a 2.4\u03c3 disagreement with Synchronism, and a sign reversal relative to the prediction.',
    learnMore: '/honest-assessment',
  },
  'delta-BIC': {
    term: 'ΔBIC',
    fullName: 'Delta Bayesian Information Criterion (BIC difference)',
    brief: 'The BIC difference between two models. ΔBIC > 10 = very strong evidence against the worse model; ΔBIC=+184 (point estimate) or ≥+33 (conservative) both far exceed this threshold.',
    explanation: 'ΔBIC = BIC_model1 − BIC_model2. Positive ΔBIC means model 2 is better. Convention: ΔBIC > 10 is "very strong evidence." In the Synchronism RAR shape test (2026-05-21): γ=2 compander vs free-γ on 2807 SPARC points gave ΔBIC=+184 (point estimate) or ≥+33 under conservative intra-galaxy correlation correction. Both values far exceed the >10 threshold — the γ=2 form is categorically rejected regardless of which figure is used. The free-γ form collapses to MOND (γ≈0.49), so either result closes the discriminating test.',
    learnMore: '/honest-assessment',
  },
  'Breit-Wigner': {
    term: 'Breit-Wigner',
    fullName: 'Breit-Wigner resonance / relativistic propagator',
    brief: 'The standard formula describing a particle resonance: probability amplitude ∝ 1/[(E−M)² + (Γ/2)²], where M is the rest mass and Γ is the decay width.',
    explanation: 'The Breit-Wigner distribution gives the probability that a particle resonance is observed at energy E, given a true mass M and total decay width Γ. The narrow-width approximation (Γ ≪ M) is the standard condition for a stable resonance appearing as a sharp peak in cross-section data — equivalent to the Källén-Lehmann spectral condition in QFT. Synchronism\'s entity criterion (Γ < m) is this narrow-width condition. The connection to the PDG resonance catalog: real resonances satisfying Γ < m appear as sharp peaks; borderline cases (σ/f₀(500), ρ(770)) sit at Γ ≈ M. The entity criterion adds an ontological interpretation (entities "exist" only when Γ < m) rather than a new mathematical condition.',
    learnMore: '/entity-criterion',
  },
  'BIC': {
    term: 'BIC',
    fullName: 'Bayesian Information Criterion',
    brief: 'A model-selection score that penalizes free parameters. Lower BIC = better model given data. \u0394BIC > 10 is strong evidence against the weaker model.',
    explanation: 'BIC = k\u00b7ln(n) \u2212 2\u00b7ln(L), where k is the number of free parameters, n is the number of data points, and L is the maximum likelihood. The \u0394BIC between two models quantifies the evidence in favor of the model with lower BIC. By convention: |\u0394BIC| < 2 = negligible evidence, 2\u20136 = positive evidence, 6\u201310 = strong evidence, >10 = very strong evidence. In the Synchronism context, the unanswered question is: does C(\u03c1) achieve a lower BIC than (a) a polynomial of similar order, (b) the MOND RAR interpolating function, or (c) other sigmoid companders (logistic, Hill, erf)? This comparison has not yet been run.',
    learnMore: '/honest-assessment',
  },
  'born-rule': {
    term: 'Born Rule',
    fullName: 'Born Rule (Quantum Probability)',
    brief: 'The quantum mechanics rule that measurement probabilities equal |\u03c8|\u00b2 \u2014 the squared amplitude of the wave function.',
    explanation: 'Standard quantum mechanics: if a system is in state \u03c8 = \u03b1|0\u27e9 + \u03b2|1\u27e9, the probability of measuring outcome "0" is |\u03b1|\u00b2 and "1" is |\u03b2|\u00b2. The Born rule is an axiom of standard QM \u2014 it cannot be derived from the Schr\u00f6dinger equation alone without additional assumptions. Synchronism\'s /born-rule page attempts to derive it from coherence conservation, but the page\'s own verdict: "no worse than Zurek\'s envariance, no better" \u2014 the derivation is a Reparametrization. No experimental deviation from |\u03c8|\u00b2 is predicted.',
    learnMore: '/born-rule',
  },
  'sigma-stat': {
    term: '\u03c3 (statistical)',
    fullName: 'Standard Deviation / Statistical Significance',
    brief: 'A number like "2.4\u03c3" means the result is 2.4 standard deviations from the expected value \u2014 roughly a 1-in-60 chance if the model is correct.',
    explanation: 'In statistics, \u03c3 (sigma) is the standard deviation \u2014 a measure of how spread out a distribution is. When scientists say a result is "2.4\u03c3 away" from a prediction, they mean: if the prediction were exactly correct, there is about a 1.6% chance of seeing a discrepancy this large by random chance. The conventional thresholds in physics are: 2\u03c3 = "interesting" (~2% chance), 3\u03c3 = "evidence" (~0.3% chance), 5\u03c3 = "discovery" (~0.00003% chance). A 2.4\u03c3 disagreement (like DESI DR1 vs Synchronism\'s f\u03c3\u2088 prediction) is taken seriously but is not by itself a definitive refutation.',
  },
  'EFE': {
    term: 'EFE',
    fullName: 'External Field Effect',
    brief: 'In MOND, a system embedded in an external gravitational field can be affected even if the internal acceleration is above the MOND threshold.',
    explanation: 'The External Field Effect (EFE) is a feature of MOND theories (Bekenstein-Milgrom 1984) with no Newtonian analog. In Newtonian gravity, external uniform fields cancel out internally (equivalence principle). In MOND, a system\'s internal dynamics depend on the total (internal + external) acceleration relative to a\u2080. This means a wide binary star system in a high-density environment (high external field) behaves more Newtonian than the same system in a low-density void. The EFE is observationally relevant for the Synchronism TEST-02 (wide binary density dependence): MOND+EFE also predicts environment-dependent dynamics, making TEST-02 potentially degenerate with MOND unless the amplitude prediction differs.',
    learnMore: '/wide-binaries',
  },
  'AIC': {
    term: 'AIC',
    fullName: 'Akaike Information Criterion',
    brief: 'A model-selection score balancing fit quality against the number of parameters. Lower AIC = better model.',
    explanation: 'AIC = 2k \u2212 2\u00b7ln(L), where k is the number of free parameters and L is the maximum likelihood. Unlike BIC, AIC does not penalize parameters as strongly (uses 2k not k\u00b7ln(n)). AIC favors models that fit well; BIC also penalizes complexity more. In the Synchronism context, running AIC across the compander family (tanh, Hill/Naka-Rushton, logistic, erf, \u03bc-law) would determine whether the tanh choice is informative or arbitrary. This comparison has not yet been run.',
    learnMore: '/coherence-function',
  },
  'BCS': {
    term: 'BCS',
    fullName: 'Bardeen-Cooper-Schrieffer (Superconductivity)',
    brief: 'The standard theory of conventional superconductivity: electrons form Cooper pairs and condense into a macroscopic quantum state.',
    explanation: 'BCS theory (Bardeen, Cooper, Schrieffer 1957) explains how phonon-mediated attraction causes electrons to form bound pairs (Cooper pairs) below a critical temperature T_c. Above T_c, electrons behave independently (low coherence). Below T_c, they condense into a macroscopic quantum state with high coherence. In Synchronism\'s \u03b3 Calculator, BCS superconductors are placed in the "Collective" regime with N_corr \u2248 10\u2077 (pairs per coherence volume) \u2014 but this is a back-fit, not a forward prediction from BCS theory itself.',
    learnMore: '/gamma-calculator',
  },
  'BEC': {
    term: 'BEC',
    fullName: 'Bose-Einstein Condensate',
    brief: 'A state of matter where bosons occupy the same quantum ground state below a critical temperature, forming a macroscopic quantum object.',
    explanation: 'A Bose-Einstein Condensate (BEC) forms when bosons (integer-spin particles: photons, He-4 atoms, Cooper pairs) are cooled below a critical temperature T_c. Unlike fermions, bosons can occupy the same quantum state, allowing a macroscopic fraction to condense into the ground state. BEC is highly coherent \u2014 N_corr is the entire condensate (10\u2076\u201310\u2079 atoms). In Synchronism\'s \u03b3 Calculator, BEC is placed in the "Collective" regime, which is correct (high N_corr, classical in Synchronism\'s non-standard usage). Note: Synchronism uses "Classical" to mean high-coherence collective behavior \u2014 the opposite of the standard physics usage.',
    learnMore: '/gamma-calculator',
  },
  'compander': {
    term: 'Compander',
    fullName: 'Compander (Companding Function)',
    brief: 'A sigmoidal function that maps a wide dynamic range onto a bounded output \u2014 the mathematical class C(\u03c1) belongs to.',
    explanation: 'A compander (compressing + expanding) maps a large input range to a bounded output via a smooth sigmoidal curve. The name comes from audio compression: \u03bc-law companding (telephone networks) uses tanh to compress loud signals without clipping quiet ones. The same class appears across disciplines: Hill function (biochemistry: oxygen binding to hemoglobin), Naka-Rushton equation (retinal response to light intensity), Kubo susceptibility (statistical mechanics near criticality). C(\u03c1) = tanh(\u03b3\u00b7ln(\u03c1/\u03c1_crit + 1)) is a compander in this class \u2014 it maps density across 80+ orders of magnitude to a bounded coherence value [0,1]. Key consequence: companders are purely evaluative (input \u2192 output), not self-consistency equations. They cannot encode universality classes, critical exponents, or spontaneous symmetry breaking \u2014 these require a feedback loop (e.g., m = tanh(\u03b2Jzm) in Ising mean-field). The site\'s /parameter-derivations page explicitly uses the term compander; this is the settled self-identification of C(\u03c1).',
    learnMore: '/coherence-function',
  },
  'kill-criterion-triggered': {
    term: 'Kill Criterion Triggered (badge)',
    fullName: 'Kill Criterion Triggered \u2014 Operational Badge',
    brief: 'A pre-registered numerical threshold has been crossed; the test is treated as failed unless a revised pre-registration is made.',
    explanation: 'A Kill Criterion is a pre-registered falsification threshold: before the test is run, a specific numerical value is set such that if the result crosses it, the prediction is treated as failed. "Kill Criterion Triggered" means that threshold was crossed. It is a stronger statement than "Failed" alone because it means the failure was anticipated and quantified in advance. In Synchronism\'s test catalog, TEST-03 (RAR environment scatter) has kill criterion R\u00b2 < 0.20 \u2014 observed R\u00b2 = 0.14, criterion triggered. TEST-04a has kill criterion f\u03c3\u2088(z=0.5) > 0.46 \u2014 DESI DR1 measures \u2248 0.55, criterion triggered. Note: "Kill Criterion Triggered" and "Speculative" are mutually exclusive \u2014 Speculative means no quantitative test has been defined; Kill Triggered means one was defined and crossed.',
    learnMore: '/tier-1-existing',
  },
  'mond-shared': {
    term: 'MOND-shared (badge)',
    fullName: 'MOND-shared \u2014 Non-Discriminating Test',
    brief: 'Synchronism and MOND make identical predictions for this test; the outcome cannot discriminate between them.',
    explanation: 'Some Tier-1 tests cannot distinguish Synchronism from MOND regardless of outcome, because both frameworks make the same prediction in that regime. These are labeled "MOND-shared." Examples: TEST-09 (BTFR slope variation with regime) \u2014 Milgrom (1983) and McGaugh (2012) already predict the same regime-dependent slope; TEST-10 (dwarf galaxy dark matter dominance) \u2014 standard MOND predicts the same pattern. A MOND-shared test is not useless \u2014 it tests both frameworks against data \u2014 but it cannot provide evidence for Synchronism over MOND. The site uses this badge on /tier-1-existing to distinguish tests that discriminate (potentially) from tests that do not.',
    learnMore: '/tier-1-existing',
  },
  'withdrawn': {
    term: 'Withdrawn (badge)',
    fullName: 'Withdrawn \u2014 Prediction Retired',
    brief: 'A prediction or test has been voluntarily retired because it was found to be contradicted by the framework itself, physically unmotivated, or replaced by a better formulation.',
    explanation: 'A Withdrawn prediction means the framework itself has disowned the test \u2014 not because external data refuted it, but because internal analysis showed it was either (a) contradicted by another part of the framework, (b) unmotivated (no derivation of the predicted amplitude), or (c) superseded by a more precise test. In Synchronism\'s test catalog: TEST-04 (BAO coherence modulation) was withdrawn because (1) Session 107 contradicts it internally, (2) the predicted effect (10\u207b\u2074) is 600\u00d7 below standard nonlinear BAO shifts and thus unmotivated, and (3) the kill criterion of 10\u207b\u2075 is smaller than current measurement precision. Withdrawn differs from Failed: failure comes from data; withdrawal comes from the framework itself.',
    learnMore: '/tier-1-existing',
  },
  'session': {
    term: 'Session',
    fullName: 'Session (research unit)',
    brief: 'One autonomous AI research exchange in the Synchronism archive \u2014 a claim worked, challenged, and resolved. Sessions are numbered (e.g. "Session 107") and roughly chronological.',
    explanation: 'The research archive was produced by 3,308 autonomous AI sessions. Each session is one unit of work: a derivation attempted, a claim stress-tested, a dataset analyzed. Site citations like "Session 107" point to the archive document with that number. Session count measures activity, not validity \u2014 the site\'s own audit found the number of sessions has no bearing on whether a result is correct (several headline numbers propagated for hundreds of sessions before anyone re-ran the underlying computation).',
    learnMore: '/research-philosophy',
  },
  'tier': {
    term: 'Tier (test classification)',
    fullName: 'Tier 1 / Tier 2 \u2014 Test Tiers',
    brief: 'Tier 1: falsification tests runnable against existing public data (Gaia, SPARC, DESI). Tier 2: exploratory hypotheses lacking a derived amplitude or mechanism \u2014 not yet falsifiable as stated.',
    explanation: 'The tier system classifies proposed tests by readiness, not importance. Tier 1 means existing data could in principle decide the test now: a stated prediction, a stated kill criterion, and a public dataset. Tier 2 means the idea is exploratory \u2014 no derived amplitude, no specified mechanism, or no meaningful kill criterion yet (e.g. TEST-07 cosmic interference, recommended for demotion to Tier 2 by the site\'s own audit). There is no Tier 3. The only Tier-1 listing is on the Tier 1: Existing Data page.',
    learnMore: '/tier-1-existing',
  },
};

export function getTerm(key: string): TermDefinition | undefined {
  return terms[key];
}

export function getAllTerms(): TermDefinition[] {
  return Object.values(terms).sort((a, b) =>
    a.fullName.toLowerCase().localeCompare(b.fullName.toLowerCase())
  );
}
